#!/usr/bin/env python
"""
Update - push constraints

for production env push must be a tag
"""
import os
import sys

from .utils import abort, get_environment, parse_git_ref


if __name__ == '__main__':
    # Remove GIT_DIR of os.environ, if present
    if 'GIT_DIR' in os.environ:
        os.environ.pop('GIT_DIR')

    # Get environment based on bare path
    environment = get_environment(os.getcwd())
    if environment not in ('dev', 'staging', 'production'):
        abort('Unknown environment: {0}'.format(environment), 2)

    # Parse git_ref being pushed
    ref_type, ref_name = parse_git_ref(sys.argv[1])

    # Production only deploys tags
    if environment == 'production' and ref_type != 'tags':
        abort('Only tags can be deployed to production', 1)

